import '~/styles/globals.css';

import { type Metadata } from 'next';
import { Geist } from 'next/font/google';

import { TRPCReactProvider } from '~/trpc/react';
import { ThemeProvider } from '~/components/theme-provider';
import { AppHeader } from '~/components/appHeader';
import { Button } from '~/components/ui/button';
import { Heart } from 'lucide-react';
import { FABDonate } from '~/components/fabDonate';

export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const geist = Geist({
    subsets: ['latin'],
    variable: '--font-geist-sans',
});

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang='en' className={`${geist.variable}`} suppressHydrationWarning>
            <body className='flex min-h-screen flex-col'>
                <TRPCReactProvider>
                    <ThemeProvider attribute={'class'} defaultTheme='system' enableSystem>
                        <AppHeader />
                        {children}
                    </ThemeProvider>
                </TRPCReactProvider>
                <div id={'portal'} />
                <FABDonate />
            </body>
        </html>
    );
}
