import '~/styles/globals.css';

import { type Metadata } from 'next';
import { Geist } from 'next/font/google';

import { TRPCReactProvider } from '~/trpc/react';
import { ThemeProvider } from '~/components/theme-provider';
import { Button } from '~/components/ui/button';
import { ThemeToggle } from '~/components/theme-toggle';
import {
    DropdownMenu,
    DropdownMenuTrigger,
    DropdownMenuContent,
    DropdownMenuItem,
} from '~/components/ui/dropdown-menu';
import { addPluginHubLink } from '~/lib/alt1';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const geist = Geist({
    subsets: ['latin'],
    variable: '--font-geist-sans',
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang='en' className={`${geist.variable}`} suppressHydrationWarning>
            <body className='flex min-h-screen flex-col'>
                <TRPCReactProvider>
                    <ThemeProvider attribute={'class'} defaultTheme='system' enableSystem>
                        <div className='flex items-center justify-between px-2 pt-2'>
                            <h1 className='scroll-m-20 text-center text-4xl font-extrabold tracking-tight text-balance'>
                                Plugin Hub
                            </h1>

                            <div className='flex gap-2'>
                                <Button variant={'outline'} asChild>
                                    <Link href={'/plugins'}>My Repos</Link>
                                </Button>
                                <DropdownMenu>
                                    <DropdownMenuTrigger>
                                        <Button variant={'outline'}>Help</Button>
                                    </DropdownMenuTrigger>
                                    <DropdownMenuContent>
                                        <DropdownMenuItem>Discord</DropdownMenuItem>
                                        <DropdownMenuItem asChild>
                                            <Link href={addPluginHubLink()}>Add to Alt1</Link>
                                        </DropdownMenuItem>
                                        <DropdownMenuItem asChild>
                                            <Link
                                                href={'http://localhost:3000'}
                                                target='_blank'
                                                rel='noopener noreferrer'
                                            >
                                                Open in Browser
                                            </Link>
                                        </DropdownMenuItem>
                                    </DropdownMenuContent>
                                </DropdownMenu>
                                <ThemeToggle />
                            </div>
                        </div>
                        {children}
                    </ThemeProvider>
                </TRPCReactProvider>
            </body>
        </html>
    );
}
